import {statuses,days,shifts,type Data,type Table,type Patient,type Student,type Appointment,type Assignment} from './types';
export const emptyData:Data={patients:[],students:[],appointments:[],assignments:[]};
export function activeCount(data:Data,id:string){return data.assignments.filter(a=>a.student_id===id&&!a.ended_on).length}
export function eligible(p:Patient){return p.age>=7&&p.details.atitus_student===false&&p.details.employee===false&&p.details.psychology_relative===false}
export function perCapita(p:Patient){const n=Number(p.details.members);return n>0&&p.details.income!==null&&p.details.income!==undefined&&p.details.income!==''?Number(p.details.income)/n:null}
export function compatible(p:Patient,s:Student){return s.availability.filter(slot=>{const [day,h]=slot.split(' - ');const hour=parseInt(h);const shift=hour>=8&&hour<12?'manhã':hour>=13&&hour<17?'tarde':hour>=18&&hour<21?'noite':null;return shift&&p.availability.includes(`${day} - ${shift}`)})}
export function validate(table:Table,row:Data[Table][number],data:Data):string[]{
 const errors:string[]=[];
 if(table==='patients'||table==='students'){const r=row as Patient|Student;if(!Array.isArray(r.availability)||r.availability.some(v=>{const [d,t]=v.split(' - ');return !days.includes(d)||(table==='patients'?!shifts.includes(t):!Array.from({length:14},(_,i)=>String(i+8).padStart(2,'0')+'h').includes(t))}))errors.push('Disponibilidade inválida: confira dia e horário.');}
 if(table==='patients'){const p=row as Patient;if(!statuses.includes(p.status))errors.push('Situação inválida.');if(data.assignments.some(a=>a.patient_id===p.id&&!a.ended_on)&&(p.status!=='Em atendimento'||!eligible(p)))errors.push('Encerre o vínculo ativo antes de alterar situação ou impedimentos.');}
 if(table==='appointments'){const a=row as Appointment;if(!['Triagem','Sessão'].includes(a.kind)||!['Agendado','Realizado','Faltou','Cancelado'].includes(a.status))errors.push('Tipo ou situação de agendamento inválido.');}
 if(table==='assignments'){const a=row as Assignment,old=data.assignments.find(v=>v.id===a.id);if(old&&(old.patient_id!==a.patient_id||old.student_id!==a.student_id||old.ended_on!==null))errors.push('Histórico de vínculos encerrados é imutável.');if(!/^\d{4}-\d{2}-\d{2}$/.test(a.started_on)||Number.isNaN(Date.parse(a.started_on))||(a.ended_on&&(!/^\d{4}-\d{2}-\d{2}$/.test(a.ended_on)||Number.isNaN(Date.parse(a.ended_on))||a.ended_on<a.started_on)))errors.push('Confira as datas do vínculo.');}
 if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(row.id))errors.push('Identificador inválido.');
 if(table==='patients'){const p=row as Patient;if(!p.name?.trim())errors.push('Informe o nome.');if(!Number.isInteger(p.age)||p.age<0||p.age>125)errors.push('Informe uma idade válida.');if(p.details.members!==null&&p.details.members!==undefined&&p.details.members!==''&&(!Number.isInteger(Number(p.details.members))||Number(p.details.members)<1))errors.push('Integrantes deve ser um inteiro maior que zero.');if(p.details.income!==undefined&&p.details.income!==null&&Number(p.details.income)<0)errors.push('Renda não pode ser negativa.');}
 if(table==='students'){const s=row as Student;if(!s.name?.trim()||!s.supervisor?.trim())errors.push('Nome e supervisora são obrigatórios.');if(!['Clínico 1','Clínico 2'].includes(s.semester))errors.push('Semestre inválido.');if(!Number.isInteger(s.declared_count)||s.declared_count<0)errors.push('Quantidade declarada inválida.');}
 if(table==='assignments'){const a=row as Assignment;const p=data.patients.find(p=>p.id===a.patient_id),s=data.students.find(s=>s.id===a.student_id);if(!p||!s)errors.push('Paciente ou aluno não encontrado.');if(!a.ended_on){if(p&&!eligible(p))errors.push('Confira os critérios de idade e vínculo com a Atitus antes de alocar.');if(s&&!s.institution_verified)errors.push('Confirme o vínculo do aluno com a Atitus.');if(data.assignments.some(v=>v.id!==a.id&&v.patient_id===a.patient_id&&!v.ended_on))errors.push('Paciente já possui vínculo ativo.');}else if(!a.reason?.trim())errors.push('Informe o motivo do encerramento.');}
 if(table==='appointments'){const a=row as Appointment;const start=new Date(a.start).getTime(),end=new Date(a.end).getTime();if(!Number.isFinite(start)||!Number.isFinite(end)||end<=start)errors.push('Confira o início e o fim.');if(!data.patients.some(p=>p.id===a.patient_id))errors.push('Selecione um paciente.');if(a.student_id&&!data.students.some(s=>s.id===a.student_id&&s.institution_verified))errors.push('Aluno sem vínculo institucional confirmado.');if(a.status!=='Cancelado'&&data.appointments.some(b=>b.id!==a.id&&b.status!=='Cancelado'&&start<new Date(b.end).getTime()&&end>new Date(b.start).getTime()&&(a.patient_id===b.patient_id||(a.student_id&&a.student_id===b.student_id)||(a.room.trim()&&a.room===b.room))))errors.push('Conflito de horário com paciente, aluno ou sala.');}
 return errors;
}
export function applyRows(data:Data,table:Table,rows:Data[Table]):Data{const next=structuredClone(data);for(const row of rows){const errors=validate(table,row,next);if(errors.length)throw new Error(errors.join(' '));const list=next[table] as Data[Table][number][];const i=list.findIndex(r=>r.id===row.id);if(i<0)list.push(row);else list[i]=row;if(table==='assignments'){const a=row as Assignment;const patient=next.patients.find(p=>p.id===a.patient_id);if(patient)patient.status=a.ended_on?'Encerrado':'Em atendimento';if(a.ended_on)next.appointments=next.appointments.map(b=>b.patient_id===a.patient_id&&b.student_id===a.student_id&&b.kind==='Sessão'&&b.status==='Agendado'&&new Date(b.start)>new Date()?{...b,status:'Cancelado'}:b);}}
 for(const r of table==='appointments'?rows:[]){const a=r as Appointment;const p=next.patients.find(p=>p.id===a.patient_id);if(p&&a.kind==='Triagem'&&['Agendado','Realizado'].includes(a.status)&&['Aguardando contato','Triagem agendada','Triagem realizada'].includes(p.status))p.status=a.status==='Realizado'?'Triagem realizada':'Triagem agendada';}
 return next;
}
