"use client";
import {useEffect,useState} from 'react';
import {Activity,ShieldCheck} from 'lucide-react';
import {supabase} from '../lib/supabase';
export function Auth({onReady}:{onReady:()=>void}){const [step,setStep]=useState('login'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[factor,setFactor]=useState(''),[qr,setQr]=useState(''),[secret,setSecret]=useState('');
 useEffect(()=>{if(!supabase)return;void supabase.auth.getSession().then(({data})=>{if(data.session)setStep('password')});const {data:{subscription}}=supabase.auth.onAuthStateChange(event=>{if(event==='PASSWORD_RECOVERY')setStep('password');if(event==='SIGNED_OUT'){setStep('login');setFactor('');setQr('');setSecret('')}});return()=>subscription.unsubscribe()},[]);
 async function password(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase)return;setBusy(true);setError('');const f=new FormData(e.currentTarget),value=String(f.get('password'));if(value!==f.get('confirm')){setError('As senhas não coincidem.');setBusy(false);return}try{const {error}=await supabase.auth.updateUser({password:value});if(error)throw error;await supabase.auth.signOut();setStep('login');setError('Senha definida. Entre com seu e-mail e a nova senha.')}catch{setError('Não foi possível definir a senha. Solicite um novo link de acesso.')}finally{setBusy(false)}}
 async function login(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase)return;setBusy(true);setError('');const f=new FormData(e.currentTarget);try{const {error}=await supabase.auth.signInWithPassword({email:String(f.get('email')),password:String(f.get('password'))});if(error)throw error;const {data,error:factorError}=await supabase.auth.mfa.listFactors();if(factorError)throw factorError;const verified=data.totp.find(f=>f.status==='verified');if(verified){setFactor(verified.id);setStep('verify')}else{const {data:enrollment,error}=await supabase.auth.mfa.enroll({factorType:'totp',friendlyName:'Sinapsi '+new Date().toISOString()});if(error)throw error;setFactor(enrollment.id);setQr(enrollment.totp.qr_code);setSecret(enrollment.totp.secret);setStep('verify')}}catch{setError('Não foi possível entrar. Confira suas credenciais e tente novamente.')}finally{setBusy(false)}}
 async function verify(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase)return;setBusy(true);setError('');try{const {error}=await supabase.auth.mfa.challengeAndVerify({factorId:factor,code:String(new FormData(e.currentTarget).get('code'))});if(error)throw error;onReady()}catch{setError('Código inválido ou expirado. Tente o próximo código do aplicativo.')}finally{setBusy(false)}}
 return <div className="auth-page"><section className="auth-card"><a className="brand" href="/"><Activity/>sinapsi<span>.</span></a><div className="auth-title"><ShieldCheck size={27}/><h1>{step==='password'?'Defina sua senha':step==='login'?'Acesso à recepção':'Verificação em duas etapas'}</h1><p>{step==='password'?'Use uma senha exclusiva, com pelo menos 12 caracteres.':step==='login'?'Entre com sua conta autorizada.':'Use o código do seu aplicativo autenticador.'}</p></div><form onSubmit={step==='password'?password:step==='login'?login:verify}>{step==='password'?<><label className="field"><span>Nova senha</span><input name="password" type="password" minLength={12} required autoComplete="new-password"/></label><label className="field"><span>Confirme a senha</span><input name="confirm" type="password" minLength={12} required autoComplete="new-password"/></label></>:step==='login'?<><label className="field"><span>E-mail</span><input name="email" type="email" required autoComplete="username"/></label><label className="field"><span>Senha</span><input name="password" type="password" required autoComplete="current-password"/></label></>:<>{qr&&<><img alt="QR code para configurar o autenticador" className="qr" src={qr}/><p className="form-note">Cadastre este QR code no seu autenticador. Chave manual:</p><code className="secret">{secret}</code></>}<label className="field"><span>Código de 6 dígitos</span><input name="code" inputMode="numeric" pattern="[0-9]{6}" autoComplete="one-time-code" required/></label></>}{error&&<p className="error" role="alert">{error}</p>}<button className="primary" disabled={busy}>{busy?'Verificando…':step==='password'?'Salvar senha':step==='login'?'Entrar':'Confirmar código'}</button></form><p className="form-note">Contas criadas apenas pelo administrador. Para recuperar acesso, contate a administração.</p></section></div>
}
