"use client";
import {useState} from 'react';
import type {Data,Table,Patient,Student} from '../lib/types';
import {days} from '../lib/types';
import {applyRows} from '../lib/domain';
type Column={key:string;label:string};
const common=[{key:'id',label:'ID'},{key:'name',label:'Nome completo'}];
export const columns:Record<Table,Column[]>={
 patients:[...common,{key:'age',label:'Idade'},{key:'status',label:'Situação'},{key:'availability',label:'Disponibilidade'},{key:'guardian',label:'Responsável'},{key:'reason',label:'Motivo da busca'},{key:'income',label:'Renda familiar total'},{key:'members',label:'Quantidade de integrantes da família'},{key:'phone',label:'Telefone'},{key:'emergency',label:'Contato de emergência'},{key:'email',label:'E-mail'},{key:'observer',label:'Autoriza observador'},{key:'atitus_link',label:'Vínculo com Atitus (resposta original)'},{key:'atitus_student',label:'É estudante Atitus'},{key:'employee',label:'É funcionário Atitus'},{key:'psychology_relative',label:'Familiar de aluno de Psicologia'},{key:'bolsa',label:'Bolsa Família'},{key:'declaration',label:'Declaração de veracidade e comprovante'}],
 students:[...common,{key:'supervisor',label:'Professora supervisora'},{key:'semester',label:'Semestre de estágio'},{key:'declared_count',label:'Pacientes declarados'},{key:'institution_verified',label:'Vínculo Atitus confirmado'},{key:'reconciled',label:'Vínculos existentes conferidos'},{key:'availability',label:'Disponibilidade'},...days.map(d=>({key:d,label:`Disponibilidade ${d}`}))],
 appointments:[{key:'id',label:'ID'},{key:'patient_id',label:'ID do paciente'},{key:'student_id',label:'ID do aluno'},{key:'start',label:'Início (ISO com fuso)'},{key:'end',label:'Fim (ISO com fuso)'},{key:'kind',label:'Tipo'},{key:'status',label:'Situação'},{key:'room',label:'Sala'}],
 assignments:[{key:'id',label:'ID'},{key:'patient_id',label:'ID do paciente'},{key:'student_id',label:'ID do aluno'},{key:'started_on',label:'Data de início'},{key:'ended_on',label:'Data de encerramento'},{key:'reason',label:'Motivo do encerramento'}]
};
const names:Record<Table,string>={patients:'Pacientes',students:'Alunos',appointments:'Agenda',assignments:'Vínculos'};
const norm=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
function flatten(table:Table,row:Data[Table][number]):Record<string,unknown>{const r={...row} as Record<string,unknown>;if(table==='patients')Object.assign(r,(row as Patient).details);if(Array.isArray(r.availability))r.availability=r.availability.join('; ');for(const day of days)r[day]=table==='students'?(row as Student).availability.filter(v=>v.startsWith(day+' - ')).map(v=>v.split(' - ')[1]).join('; '):'';return r;}
export async function exportExcel(table:Table|'overview',data:Data,rows:Data[Table]=[],template=false,includeSensitive=false){const {default:ExcelJS}=await import('exceljs');const wb=new ExcelJS.Workbook();wb.creator='Sinapsi';const tables:Table[]=table==='overview'?['patients','students','appointments','assignments']:[table];for(const t of tables){const sheet=wb.addWorksheet(names[t]);const exportedColumns=columns[t].filter(c=>includeSensitive||t!=='patients'||c.key!=='reason');sheet.columns=exportedColumns.map(c=>({header:c.label,key:c.key,width:c.key==='id'||c.key.endsWith('_id')?38:26}));if(!template)for(const row of table==='overview'?data[t]:rows){const source=flatten(t,row);sheet.addRow(Object.fromEntries(exportedColumns.map(c=>{const v=source[c.key];return [c.key,typeof v==='boolean'?(v?'Sim':'Não'):v??'']})))}sheet.getRow(1).font={bold:true,color:{argb:'FFFFFFFF'}};sheet.getRow(1).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF176B4E'}};sheet.views=[{state:'frozen',ySplit:1}];sheet.autoFilter={from:'A1',to:{row:Math.max(1,sheet.rowCount),column:exportedColumns.length}}}const bytes=await wb.xlsx.writeBuffer();const url=URL.createObjectURL(new Blob([new Uint8Array(bytes)],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}));const a=document.createElement('a');a.href=url;a.download=`Sinapsi-${template?'modelo-':''}${table}-${new Date().toISOString().slice(0,10)}.xlsx`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function guess(key:string,label:string,headers:string[]){const direct=headers.find(h=>norm(h)===norm(label)||norm(h)===norm(key));if(direct)return direct;const patterns:Record<string,string[]>={name:['nome completo'],age:['idade'],supervisor:['professora supervisora'],semester:['semestre de estagio'],declared_count:['quantos pacientes'],guardian:['nome do responsavel'],reason:['principal motivo'],income:['renda familiar total'],phone:['telefone'],emergency:['contato de emergencia'],email:['e-mail'],observer:['observador'],atitus_link:['familiar direto tem vinculo'],bolsa:['bolsa familia'],declaration:['declaro que'],availability:['disponibilidade de horarios para atendimentos futuros']};return headers.find(h=>(patterns[key]||days.includes(key)?patterns[key]||[norm(key)+'-feira']:[]).some(p=>norm(h).includes(p)))||'';}
export function ExcelPanel({initial,data,onSave,onClose}:{initial:Table;data:Data;onSave:(t:Table,r:Data[Table])=>Promise<void>;onClose:()=>void}){
 const [table,setTable]=useState<Table>(initial),[sheets,setSheets]=useState<{name:string;rows:Record<string,string>[]}[]>([]),[sheetIndex,setSheetIndex]=useState(0),[mapping,setMapping]=useState<Record<string,string>>({}),[preview,setPreview]=useState<Data[Table]>([]),[errors,setErrors]=useState<string[]>([]),[busy,setBusy]=useState(false),[updates,setUpdates]=useState(false);
 const sheet=sheets[sheetIndex],headers=sheet?.rows[0]?Object.keys(sheet.rows[0]):[];
 function selectSheet(index:number,t=table){setSheetIndex(index);setPreview([]);const h=Object.keys(sheets[index]?.rows[0]||{});setMapping(Object.fromEntries(columns[t].map(c=>[c.key,guess(c.key,c.label,h)])))}
 async function fileChanged(file:File|undefined){if(!file)return;setErrors([]);setPreview([]);setBusy(true);try{if(!file.name.toLowerCase().endsWith('.xlsx'))throw new Error('Use uma planilha .xlsx.');if(file.size>2*1024*1024)throw new Error('Limite de 2 MB por arquivo. Divida a planilha em arquivos menores.');const {default:ExcelJS}=await import('exceljs');const wb=new ExcelJS.Workbook();await wb.xlsx.load(await file.arrayBuffer());const parsed=wb.worksheets.map(ws=>{if(ws.rowCount>501)throw new Error('Máximo de 500 linhas por aba.');const headers:string[]=[];ws.getRow(1).eachCell({includeEmpty:true},(c,i)=>{headers[i-1]=c.text.trim()||`Coluna ${i}`});if(new Set(headers).size!==headers.length)throw new Error('Há cabeçalhos repetidos. Renomeie as colunas.');const rows:Record<string,string>[]=[];ws.eachRow((r,i)=>{if(i===1)return;const obj:Record<string,string>={};headers.forEach((h,j)=>{const c=r.getCell(j+1);if(c.type===ExcelJS.ValueType.Formula)throw new Error(`Fórmula na linha ${i}: converta em valor antes de importar.`);obj[h]=c.value instanceof Date?c.value.toISOString():c.text});if(Object.values(obj).some(v=>v.trim()))rows.push(obj)});return {name:ws.name,rows}});setSheets(parsed);setSheetIndex(0);const h=Object.keys(parsed[0]?.rows[0]||{});setMapping(Object.fromEntries(columns[table].map(c=>[c.key,guess(c.key,c.label,h)])))}catch(e){setErrors([e instanceof Error?e.message:'Não foi possível ler a planilha.']);setSheets([])}finally{setBusy(false)}}
 function validate(){setPreview([]);const problems:string[]=[];const rows:Data[Table][number][]=[];let next=structuredClone(data);const seen=new Set<string>();for(const [index,raw] of (sheet?.rows||[]).entries()){try{const get=(key:string)=>raw[mapping[key]]?.trim()||'';const id=get('id')||crypto.randomUUID();if(seen.has(id))throw new Error('ID repetido no arquivo.');seen.add(id);const previous=data[table].find(r=>r.id===id);if(previous&&!updates)throw new Error('ID já existe. Autorize atualização por ID ou remova a linha.');const yes=(k:string)=>norm(get(k))==='sim';const tri=(k:string)=>get(k)===''?null:yes(k)?true:norm(get(k))==='nao'?false:(()=>{throw new Error(`${k}: use Sim ou Não.`)})();const list=(text:string)=>text.split(/[;,]/).map(s=>s.trim().replace(/\s*-\s*/,' - ')).filter(Boolean);let row:Data[Table][number];
 if(table==='patients'){const old=previous as Patient|undefined;const details={...old?.details};for(const key of ['guardian','reason','phone','email','emergency','atitus_link','observer','bolsa','declaration'])if(mapping[key])details[key]=get(key);for(const key of ['atitus_student','employee','psychology_relative'])if(mapping[key])details[key]=tri(key);for(const key of ['income','members'])if(mapping[key]){const v=get(key).replace(/R\$\s*/g,'');details[key]=v===''?null:Number(v.includes(',')?v.replace(/\./g,'').replace(',','.'):v);if(details[key]!==null&&!Number.isFinite(details[key]))throw new Error(`Valor inválido em ${key}.`)}row={id,name:get('name')||old?.name||'',age:mapping.age?(get('age')===''?NaN:Number(get('age'))):old?.age??NaN,status:get('status')||old?.status||'Aguardando contato',availability:mapping.availability?list(get('availability')):old?.availability||[],details};}
 else if(table==='students'){const old=previous as Student|undefined;let availability=mapping.availability?list(get('availability')):old?.availability||[];for(const d of days)if(mapping[d]){const text=get(d);if(norm(text).includes('nao tenho')&&/\d/.test(text))throw new Error(`Disponibilidade contraditória em ${d}.`);availability=availability.filter(v=>!v.startsWith(d+' - '));if(!norm(text).includes('nao tenho'))availability.push(...list(text).map(v=>`${d} - ${v}`))}row={id,name:get('name')||old?.name||'',supervisor:get('supervisor')||old?.supervisor||'',semester:get('semester')||old?.semester||'',declared_count:mapping.declared_count?Number(get('declared_count')):old?.declared_count??0,institution_verified:mapping.institution_verified?yes('institution_verified'):old?.institution_verified??false,reconciled:mapping.reconciled?yes('reconciled'):old?.reconciled??false,availability};}
 else if(table==='appointments'){if(!/([+-]\d{2}:\d{2}|Z)$/.test(get('start'))||!/([+-]\d{2}:\d{2}|Z)$/.test(get('end')))throw new Error('Início e fim devem incluir fuso, por exemplo 2026-09-14T09:00:00-03:00.');row={id,patient_id:get('patient_id'),student_id:get('student_id')||null,start:get('start'),end:get('end'),kind:get('kind'),status:get('status')||'Agendado',room:get('room')};}
 else row={id,patient_id:get('patient_id'),student_id:get('student_id'),started_on:get('started_on').slice(0,10),ended_on:get('ended_on').slice(0,10)||null,reason:get('reason')};
 if('name' in row&&!previous&&(next[table] as {id:string;name?:string}[]).some(r=>norm(r.name||'')===norm(row.name)))throw new Error('Possível duplicidade pelo nome. Confira e use o ID existente para atualizar.');next=applyRows(next,table,[row] as Data[Table]);rows.push(row);
 }catch(e){problems.push(`Linha ${index+2}: ${e instanceof Error?e.message:'Dados inválidos.'}`)}}setErrors(problems);if(!problems.length)setPreview(rows as Data[Table]);}
 return <div><p className="form-note">Escolha a entidade, confira as colunas e valide antes de importar. Nenhuma alteração é feita até a confirmação. Colunas ausentes em uma atualização preservam o valor anterior.</p><div className="form-grid"><label className="field"><span>Importar para</span><select value={table} onChange={e=>{const t=e.target.value as Table;setTable(t);selectSheet(sheetIndex,t)}}>{Object.entries(names).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="field"><span>Planilha Excel (.xlsx)</span><input type="file" accept=".xlsx" onChange={e=>void fileChanged(e.target.files?.[0])}/></label></div><button className="text-button" onClick={()=>void exportExcel(table,data,[],true,true)}>Baixar modelo vazio</button>{sheets.length>0&&<><label className="field"><span>Aba da planilha</span><select value={sheetIndex} onChange={e=>selectSheet(Number(e.target.value))}>{sheets.map((s,i)=><option key={i} value={i}>{s.name} ({s.rows.length} linhas)</option>)}</select></label><h3>Correspondência das colunas</h3><div className="form-grid mapping">{columns[table].map(c=><label className="field" key={c.key}><span>{c.label}</span><select value={mapping[c.key]||''} onChange={e=>{setMapping({...mapping,[c.key]:e.target.value});setPreview([])}}><option value="">Não informada</option>{headers.map(h=><option key={h}>{h}</option>)}</select></label>)}</div><label className="checkbox-line"><input type="checkbox" checked={updates} onChange={e=>{setUpdates(e.target.checked);setPreview([])}}/>Permitir atualizar registros identificados pelo mesmo ID</label><button className="secondary" onClick={validate}>Validar {sheet?.rows.length} linhas</button></>}{errors.length>0&&<div className="error" role="alert">{errors.slice(0,15).map((e,i)=><p key={i}>{e}</p>)}{errors.length>15&&<p>Mais {errors.length-15} erros.</p>}</div>}{preview.length>0&&<><h3>Prévia · {preview.length} registros válidos</h3><div className="table-wrap preview"><table><thead><tr>{columns[table].slice(0,5).map(c=><th key={c.key}>{c.label}</th>)}</tr></thead><tbody>{preview.slice(0,10).map(row=><tr key={row.id}>{columns[table].slice(0,5).map(c=><td key={c.key}>{String(flatten(table,row)[c.key]??'')}</td>)}</tr>)}</tbody></table></div><p className="form-note">{preview.length>10?'Exibindo as primeiras 10 linhas. ':''}O lote inteiro será salvo ou nenhuma linha será alterada.</p></>}<div className="form-actions"><button className="secondary" onClick={onClose}>Cancelar</button><button className="primary" disabled={!preview.length||busy} onClick={async()=>{setBusy(true);try{await onSave(table,preview);onClose()}catch(e){setErrors([e instanceof Error?e.message:'Falha ao importar.'])}finally{setBusy(false)}}}>{busy?'Processando…':'Confirmar importação'}</button></div></div>
}
