"use client";
import {useState} from 'react';
import {days,shifts,statuses,type Data,type Table,type Patient,type Student,type Appointment,type Assignment} from '../lib/types';
import {perCapita} from '../lib/domain';
export function RecordForm({table,record,data,onSave,onClose}:{table:Table;record?:Data[Table][number];data:Data;onSave:(t:Table,r:Data[Table])=>Promise<void>;onClose:()=>void}){
 const [busy,setBusy]=useState(false),[error,setError]=useState('');
 const [slots,setSlots]=useState<string[]>((record as Patient|Student)?.availability||[]);
 const p=record as Patient|undefined,s=record as Student|undefined,a=record as Appointment|undefined;
 const toggle=(v:string)=>setSlots(old=>old.includes(v)?old.filter(x=>x!==v):[...old,v]);
 const field=(label:string,name:string,value:unknown='',type='text',required=false)=><label className="field" key={name}><span>{label}{required?' *':''}</span><input name={name} type={type} defaultValue={String(value??'')} required={required} min={type==='number'?0:undefined} step={name==='income'?'0.01':undefined}/></label>;
 const select=(label:string,name:string,value:unknown,options:string[],required=false)=><label className="field" key={name}><span>{label}{required?' *':''}</span><select name={name} defaultValue={String(value??'')} required={required}><option value="">A conferir</option>{options.map(v=><option key={v}>{v}</option>)}</select></label>;
 const bool=(key:string)=>p?.details[key]===true?'Sim':p?.details[key]===false?'Não':'';
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);const str=(k:string)=>String(f.get(k)||'');const num=(k:string)=>str(k)===''?null:Number(str(k));let row:Data[Table][number];
 if(table==='patients'){const details={...p?.details};for(const k of ['guardian','reason','phone','email','emergency','atitus_link','observer','bolsa','declaration'])details[k]=str(k);details.income=num('income');details.members=num('members');for(const k of ['atitus_student','employee','psychology_relative'])details[k]=str(k)===''?null:str(k)==='Sim';row={id:p?.id||crypto.randomUUID(),name:str('name'),age:Number(str('age')),status:str('status'),availability:slots,details};}
 else if(table==='students')row={id:s?.id||crypto.randomUUID(),name:str('name'),supervisor:str('supervisor'),semester:str('semester'),availability:slots,institution_verified:str('institution_verified')==='Sim',declared_count:Number(str('declared_count')),reconciled:str('reconciled')==='Sim'};
 else if(table==='appointments')row={id:a?.id||crypto.randomUUID(),patient_id:str('patient_id'),student_id:str('student_id')||null,start:str('start')+':00-03:00',end:str('end')+':00-03:00',kind:str('kind'),status:str('status'),room:str('room').trim()};
 else {const v=record as Assignment;row={...v,ended_on:str('ended_on'),reason:str('reason')};}
 try{await onSave(table,[row] as Data[Table]);onClose()}catch(err){setError(err instanceof Error?err.message:'Não foi possível salvar.')}finally{setBusy(false)}
 }
 const local=(value:string|undefined)=>value?new Intl.DateTimeFormat('sv-SE',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(value)).replace(' ','T'):'';
 return <form onSubmit={submit}><div className="form-grid">{table==='patients'&&<>{field('Nome completo','name',p?.name,'text',true)}{field('Idade na inscrição','age',p?.age,'number',true)}{field('Responsável, se menor','guardian',p?.details.guardian)}{field('Telefone','phone',p?.details.phone,'tel')}{field('E-mail','email',p?.details.email,'email')}{select('Situação','status',p?.status||statuses[0],statuses.filter(v=>v!=='Em atendimento'&&(!data.assignments.some(a=>a.patient_id===p?.id&&!a.ended_on)||!['Encerrado','Desistência','Encaminhado'].includes(v))).concat(p?.status==='Em atendimento'?['Em atendimento']:[]),true)}{field('Renda familiar total (R$)','income',p?.details.income,'number')}{field('Integrantes da família, incluindo paciente','members',p?.details.members,'number')}<label className="field full"><span>Motivo da busca por atendimento</span><textarea name="reason" defaultValue={String(p?.details.reason||'')} rows={3}/></label>{field('Contato de emergência: nome, vínculo e telefone','emergency',p?.details.emergency)}{field('Vínculo com a Atitus — resposta original','atitus_link',p?.details.atitus_link)}{select('É estudante da Atitus?','atitus_student',bool('atitus_student'),['Sim','Não'])}{select('É funcionário da Atitus?','employee',bool('employee'),['Sim','Não'])}{select('É familiar de aluno de Psicologia Atitus?','psychology_relative',bool('psychology_relative'),['Sim','Não'])}{select('Beneficiário de Bolsa Família?','bolsa',p?.details.bolsa,['Sim','Não'])}{select('Autoriza observador na primeira conversa?','observer',p?.details.observer,['Sim','Não'])}{select('Declara veracidade e entrega futura do comprovante?','declaration',p?.details.declaration,['Sim','Não'])}<p className="form-note full">Campos ausentes podem ser completados após a importação. A declaração não significa que o comprovante já foi entregue.</p></>}
 {table==='students'&&<>{field('Nome completo','name',s?.name,'text',true)}<label className="field"><span>Professora supervisora *</span><input name="supervisor" list="supervisors" defaultValue={s?.supervisor} required/><datalist id="supervisors">{['Mariana Ungaretti','Francielle Beria','Fernanda Cerutti','Vera Ramires'].map(v=><option key={v}>{v}</option>)}</datalist></label>{select('Semestre','semester',s?.semester||'Clínico 1',['Clínico 1','Clínico 2'],true)}{field('Pacientes declarados no formulário','declared_count',s?.declared_count??0,'number',true)}{select('Vínculo de aluno Atitus confirmado?','institution_verified',s?.institution_verified?'Sim':'Não',['Sim','Não'],true)}{select('Todos os pacientes existentes já foram vinculados no painel?','reconciled',s?.reconciled?'Sim':'Não',['Sim','Não'],true)}<p className="form-note full">A quantidade declarada é uma referência da importação. A sinalização de pacientes considera os vínculos do painel após a conferência.</p></>}
 {(table==='patients'||table==='students')&&<fieldset className="full availability"><legend>Disponibilidade semanal</legend><p className="form-note">{table==='patients'?'Manhã 08h–12h · Tarde 13h–17h · Noite 18h–21h':'Marque todos os horários disponíveis. Nenhuma seleção no dia significa sem disponibilidade.'}</p>{days.map(day=><div className="slot-day" key={day}><b>{day}</b><div>{(table==='patients'?shifts:Array.from({length:14},(_,i)=>String(i+8).padStart(2,'0')+'h')).map(time=><label className={slots.includes(`${day} - ${time}`)?'slot selected':'slot'} key={time}><input type="checkbox" aria-label={`${day} - ${time}`} checked={slots.includes(`${day} - ${time}`)} onChange={()=>toggle(`${day} - ${time}`)}/>{time}</label>)}</div></div>)}</fieldset>}
 {table==='appointments'&&<><label className="field"><span>Paciente *</span><select name="patient_id" required defaultValue={a?.patient_id||''}><option value="">Selecione</option>{data.patients.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="field"><span>Aluno</span><select name="student_id" defaultValue={a?.student_id||''}><option value="">A definir</option>{data.students.filter(s=>s.institution_verified).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>{field('Início (Porto Alegre)','start',local(a?.start),'datetime-local',true)}{field('Fim (Porto Alegre)','end',local(a?.end),'datetime-local',true)}{select('Tipo','kind',a?.kind||'Triagem',['Triagem','Sessão'],true)}{select('Situação','status',a?.status||'Agendado',['Agendado','Realizado','Faltou','Cancelado'],true)}{field('Sala','room',a?.room)}<p className="form-note full">A duração é definida em cada agendamento. Conflitos de paciente, aluno ou sala impedem salvar. Primeira consulta gratuita; demais sessões: R$ 20.</p></>}
 {table==='assignments'&&<>{field('Data de encerramento','ended_on',new Date().toISOString().slice(0,10),'date',true)}{field('Motivo administrativo','reason','','text',true)}<p className="form-note full">O vínculo fica no histórico. Sessões futuras agendadas para este vínculo serão canceladas.</p></>}</div>{table==='patients'&&p&&<section className="history"><h3>Histórico de vínculos</h3>{data.assignments.filter(a=>a.patient_id===p.id).map(a=><p className="form-note" key={a.id}>{data.students.find(s=>s.id===a.student_id)?.name} · {a.started_on} — {a.ended_on||'ativo'} {a.reason&&`· ${a.reason}`}</p>)}{!data.assignments.some(a=>a.patient_id===p.id)&&<p className="form-note">Nenhum vínculo registrado.</p>}</section>}{error&&<p role="alert" className="error">{error}</p>}<div className="form-actions"><button type="button" className="secondary" onClick={onClose}>Cancelar</button><button className="primary" disabled={busy}>{busy?'Salvando…':'Salvar'}</button></div></form>
}
