import {build} from 'esbuild';
import assert from 'node:assert/strict';
import ExcelJS from 'exceljs';
await build({entryPoints:['lib/domain.ts'],bundle:true,platform:'node',format:'esm',outfile:'.sites-runtime/domain.mjs'});
await build({entryPoints:['components/ExcelPanel.tsx'],bundle:true,platform:'node',format:'esm',packages:'external',outfile:'.sites-runtime/excel.mjs'});
const {applyRows,activeCount,compatible,emptyData,perCapita}=await import('../.sites-runtime/domain.mjs');
const {exportExcel}=await import('../.sites-runtime/excel.mjs');
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const patient=n=>({id:id(n),name:'Paciente '+n,age:20,status:'Aguardando vaga',availability:['Segunda - manhã'],details:{income:2400,members:3,reason:'=HYPERLINK("https://example.com")',atitus_student:false,employee:false,psychology_relative:false}});
const student={id:id(20),name:'Aluno',supervisor:'Supervisora',semester:'Clínico 1',availability:['Segunda - 09h','Segunda - 12h'],institution_verified:true,declared_count:0,reconciled:true};
let data=applyRows(emptyData,'patients',[patient(1),patient(2),patient(3)]);data=applyRows(data,'students',[student]);
assert.deepEqual(compatible(patient(1),student),['Segunda - 09h']);assert.equal(perCapita(patient(1)),800);assert.equal(perCapita({...patient(1),details:{income:2400}}),null);
data=applyRows(data,'assignments',[1,2,3].map(n=>({id:id(30+n),patient_id:id(n),student_id:id(20),started_on:'2026-09-11',ended_on:null,reason:''})));assert.equal(activeCount(data,id(20)),3);
assert.throws(()=>applyRows(data,'patients',[{...data.patients[0],status:'Encerrado'}]));assert.throws(()=>applyRows(data,'students',[{...student,availability:['Segunda - 99h']} ]));
data=applyRows(data,'assignments',[{...data.assignments[0],ended_on:'2026-09-12',reason:'Teste'}]);assert.equal(activeCount(data,id(20)),2);assert.equal(data.patients[0].status,'Encerrado');
let exported;URL.createObjectURL=blob=>{exported=blob;return 'blob:test'};URL.revokeObjectURL=()=>{};globalThis.document={createElement:()=>({click(){}})};
await exportExcel('patients',data,data.patients);let wb=new ExcelJS.Workbook();await wb.xlsx.load(await exported.arrayBuffer());assert.ok(!wb.worksheets[0].getRow(1).values.includes('Motivo da busca'));
await exportExcel('patients',data,data.patients,false,true);wb=new ExcelJS.Workbook();await wb.xlsx.load(await exported.arrayBuffer());const column=wb.worksheets[0].getRow(1).values.indexOf('Motivo da busca');assert.equal(wb.worksheets[0].getRow(2).getCell(column).type,ExcelJS.ValueType.String);
await exportExcel('students',data,data.students);wb=new ExcelJS.Workbook();await wb.xlsx.load(await exported.arrayBuffer());const dayCol=wb.worksheets[0].getRow(1).values.indexOf('Disponibilidade Segunda');assert.equal(wb.worksheets[0].getRow(2).getCell(dayCol).text,'09h; 12h');
console.log('PASS: distribution >2, closure, availability boundaries, unknown income, optional sensitive export, formula-safe cells, and student availability export.');
