"use client";
import {useEffect,useRef,useState} from 'react';
import {Activity,ArrowRight,CalendarDays,ClipboardList,Download,GraduationCap,LayoutDashboard,Link2,LogOut,Plus,Search,Settings2,Upload,Users,X} from 'lucide-react';
import {demoData} from '../lib/demo';
import {activeCount,applyRows,compatible,eligible,emptyData,perCapita} from '../lib/domain';
import {type Data,type Table,type Patient,type Student,type Appointment,statuses} from '../lib/types';
import {supabase} from '../lib/supabase';
import {RecordForm} from '../components/RecordForm';
import {Auth} from '../components/Auth';
import {ExcelPanel,exportExcel} from '../components/ExcelPanel';

const routes=[{n:'Visão geral',i:LayoutDashboard},{n:'Triagem',i:ClipboardList},{n:'Agenda',i:CalendarDays},{n:'Pacientes',i:Users},{n:'Alunos',i:GraduationCap},{n:'Alocação',i:Link2}];
const pageTable:Partial<Record<string,Table>>={'Triagem':'patients','Agenda':'appointments','Pacientes':'patients','Alunos':'students','Alocação':'assignments'};
const descriptions:Record<string,string>={'Visão geral':'Acompanhe os atendimentos e cuide dos próximos passos.','Triagem':'Da primeira conversa ao próximo encaminhamento.','Agenda':'Organize encontros, horários e salas.','Pacientes':'Cada pessoa, com seu cadastro e sua trajetória.','Alunos':'Disponibilidades e distribuição de pacientes.','Alocação':'Encontre horários compatíveis e organize vínculos.','Usuários':'Controle quem tem acesso à recepção.'};
function initials(name:string){return name.split(' ').map(v=>v[0]).slice(0,2).join('')}
function time(value:string){return new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Sao_Paulo',hour:'2-digit',minute:'2-digit'}).format(new Date(value))}
function date(value:string){return new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Sao_Paulo',day:'2-digit',month:'2-digit'}).format(new Date(value))}

export default function Home(){
 const [includeSensitive,setIncludeSensitive]=useState(false),[calendarMode,setCalendarMode]=useState('all'),[studentFilter,setStudentFilter]=useState('');
 const [page,setPage]=useState('Visão geral'),[data,setData]=useState<Data>(supabase?emptyData:demoData),[ready,setReady]=useState(!supabase),[loading,setLoading]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState('');
 const [operator,setOperator]=useState({name:'Administrador',role:'admin'}),[search,setSearch]=useState(''),[filter,setFilter]=useState(''),[selected,setSelected]=useState(''),[calendarDate,setCalendarDate]=useState('');
 const [modal,setModal]=useState<{table:Table;record?:Data[Table][number]}|null>(null),[excel,setExcel]=useState(false),[busy,setBusy]=useState(false),[members,setMembers]=useState<{id:string;name:string;role:string;active:boolean}[]>([]);
 const dialog=useRef<HTMLDialogElement>(null);
 const demo=!supabase;
 async function reload(){if(!supabase)return;setLoading(true);try{const {data:profiles,error:profileError}=await supabase.from('operators').select('*');if(profileError)throw profileError;const {data:user}=await supabase.auth.getUser();const own=profiles.find(p=>p.id===user.user?.id&&p.active);if(!own)throw new Error('Esta conta não tem autorização para acessar o Sinapsi.');setOperator(own);setMembers(profiles);const entries=await Promise.all((['patients','students','assignments','appointments'] as Table[]).map(async t=>{const {data:rows,error}=await supabase!.from(t).select('*').order('id');if(error)throw error;return [t,rows]}));setData(Object.fromEntries(entries) as Data);setReady(true);setError('')}catch(err){setData(emptyData);setError(err instanceof Error?err.message:'Não foi possível carregar os dados.')}finally{setLoading(false)}}
 useEffect(()=>{const onHash=()=>{const name=decodeURIComponent(location.hash.slice(1));if([...routes.map(r=>r.n),'Usuários'].includes(name))setPage(name)};onHash();window.addEventListener('hashchange',onHash);return()=>window.removeEventListener('hashchange',onHash)},[]);
 useEffect(()=>{if(modal||excel)dialog.current?.showModal();else dialog.current?.close()},[modal,excel]);
 useEffect(()=>{if(!supabase)return;const {data:{subscription}}=supabase.auth.onAuthStateChange((event)=>{if(event==='SIGNED_OUT'){setData(emptyData);setReady(false);setOperator({name:'',role:'operator'})}});return()=>subscription.unsubscribe()},[]);
 useEffect(()=>{if(!ready||demo)return;let timer:ReturnType<typeof setTimeout>;const renew=()=>{clearTimeout(timer);timer=setTimeout(()=>{void supabase?.auth.signOut();setNotice('Sessão encerrada por inatividade.')},30*60*1000)};renew();window.addEventListener('pointerdown',renew);window.addEventListener('keydown',renew);return()=>{clearTimeout(timer);window.removeEventListener('pointerdown',renew);window.removeEventListener('keydown',renew)}},[ready,demo]);
 function go(n:string){setPage(n);setSearch('');setFilter('');location.hash=encodeURIComponent(n)}
 useEffect(()=>{const ctx=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>}}).modelContext;if(!ctx?.registerTool)return;const controller=new AbortController();void Promise.resolve(ctx.registerTool({name:'navigate_sinapsi',description:'Abre uma página operacional do Sinapsi; não altera cadastros.',inputSchema:{type:'object',properties:{page:{type:'string',enum:routes.map(r=>r.n)}},required:['page'],additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:{page:string})=>{if(!routes.some(r=>r.n===input.page))throw new Error('Página inválida');go(input.page);return {page:input.page}}},{signal:controller.signal})).catch(()=>{});return()=>controller.abort()},[]);
 async function save(table:Table,rows:Data[Table]){const next=applyRows(data,table,rows);if(supabase){const {error}=await supabase.rpc('save_batch',{entity:table,rows});if(error)throw new Error(error.code==='23P01'?'Conflito de horário com paciente, aluno ou sala.':error.message);await reload()}else setData(next);setNotice(demo?'Alteração aplicada na demonstração. Será descartada ao recarregar.':'Alteração salva.');}
 const patientRows=data.patients.filter(p=>p.name.toLocaleLowerCase('pt-BR').includes(search.toLocaleLowerCase('pt-BR'))&&(!filter||p.status===filter)&&(page!=='Triagem'||['Aguardando contato','Triagem agendada','Triagem realizada','Aguardando vaga'].includes(p.status)));
 const studentRows=data.students.filter(s=>s.name.toLocaleLowerCase('pt-BR').includes(search.toLocaleLowerCase('pt-BR'))&&(!filter||(s.reconciled&&activeCount(data,s.id)<2)));
 const appointmentDay=(value:string)=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(value));
 const inCalendar=(value:string)=>{if(!calendarDate||calendarMode==='all')return true;const day=appointmentDay(value);if(calendarMode==='day')return day===calendarDate;const ref=new Date(calendarDate+'T12:00:00Z');ref.setUTCDate(ref.getUTCDate()-((ref.getUTCDay()+6)%7));const start=ref.toISOString().slice(0,10);ref.setUTCDate(ref.getUTCDate()+7);return day>=start&&day<ref.toISOString().slice(0,10)};
 const appointments=data.appointments.filter(a=>(data.patients.find(p=>p.id===a.patient_id)?.name||'').toLowerCase().includes(search.toLowerCase())&&inCalendar(a.start)&&(!studentFilter||a.student_id===studentFilter)).sort((a,b)=>new Date(a.start).getTime()-new Date(b.start).getTime());
 const chosen=data.patients.find(p=>p.id===selected);
 const pendingStudents=data.students.filter(s=>s.reconciled&&activeCount(data,s.id)<2);
 async function exportCurrent(){setBusy(true);try{const scope=pageTable[page]||'overview';const rows=scope==='patients'?patientRows:scope==='students'?studentRows:scope==='appointments'?appointments:scope==='assignments'?data.assignments:[];if(supabase){const {error}=await supabase.rpc('log_export',{entity:scope,total:scope==='overview'?Object.values(data).reduce((n,a)=>n+a.length,0):rows.length});if(error)throw error}await exportExcel(scope,data,rows,false,includeSensitive);setNotice('Planilha exportada.')}catch{setError('Não foi possível exportar a planilha. Tente novamente.')}finally{setBusy(false)}}
 async function assign(s:Student){if(!chosen)return;setBusy(true);setError('');try{await save('assignments',[{id:crypto.randomUUID(),patient_id:chosen.id,student_id:s.id,started_on:new Date().toISOString().slice(0,10),ended_on:null,reason:''}]);setSelected('')}catch(e){setError(e instanceof Error?e.message:'Não foi possível vincular.')}finally{setBusy(false)}}
 async function invite(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError('');if(!supabase){setNotice('Criação de usuários estará disponível após conectar o Supabase.');return}setBusy(true);const f=new FormData(e.currentTarget);try{const {error}=await supabase.functions.invoke('manage-users',{body:{name:String(f.get('name')),email:String(f.get('email')),redirectTo:location.origin}});if(error)throw error;setNotice('Convite enviado por e-mail.');await reload()}catch{setError('Não foi possível enviar o convite. Confira a configuração da função e do e-mail no Supabase.')}finally{setBusy(false)}}
 const newRecord=()=>setModal({table:page==='Alunos'?'students':page==='Agenda'||page==='Triagem'?'appointments':'patients'});
 if(!ready)return <>{error&&<div className="error">{error}<button className="text-button" onClick={()=>void supabase?.auth.signOut()}>Voltar ao login</button></div>}<Auth onReady={()=>void reload()}/></>;
 return <div className="shell"><aside className="sidebar"><a className="brand" href="#Vis%C3%A3o%20geral" onClick={()=>go('Visão geral')}><Activity/>sinapsi<span>.</span></a><p className="eyebrow">CLÍNICA-ESCOLA · ATITUS</p><div className="nav-label">ORGANIZAÇÃO</div><nav>{routes.map(({n,i:I})=><button key={n} className={page===n?'nav-item active':'nav-item'} onClick={()=>go(n)}><I size={19}/>{n}{n==='Triagem'&&<span className="nav-count">{data.patients.filter(p=>p.status==='Aguardando contato').length}</span>}</button>)}{operator.role==='admin'&&<button className={page==='Usuários'?'nav-item active':'nav-item'} onClick={()=>go('Usuários')}><Settings2 size={19}/>Usuários</button>}</nav><div className="sidebar-bottom"><div className="unit"><span className="status-dot"/>Porto Alegre<small>Atendimento presencial</small></div><div className="profile"><span className="avatar">{initials(operator.name)}</span><div><b>{operator.name}</b><small>{demo?'Demonstração':operator.role==='admin'?'Administrador':'Recepção'}</small></div>{!demo&&<button title="Sair" className="icon-button" onClick={()=>void supabase?.auth.signOut()}><LogOut size={17}/></button>}</div></div></aside><main><header className="topbar"><span className="breadcrumb">Recepção <span>/</span> {page}</span><span>SINAPSI · Porto Alegre</span></header><div className="workspace">{demo&&<div className="demo-banner">Demonstração · apenas dados fictícios. Alterações não são salvas ao recarregar.</div>}<div className="page-heading"><div><p className="eyebrow">{page==='Visão geral'?'SEU DIA, ORGANIZADO':'RECEPÇÃO SINAPSI'}</p><h1>{page}</h1><p>{descriptions[page]}</p></div>{page!=='Usuários'&&page!=='Alocação'&&<button className="primary" onClick={newRecord}><Plus size={18}/>{page==='Alunos'?'Novo aluno':page==='Agenda'||page==='Triagem'?'Agendar triagem / sessão':'Novo paciente'}</button>}</div>{notice&&<div className="notice" role="status">{notice}<button aria-label="Fechar aviso" onClick={()=>setNotice('')}><X size={15}/></button></div>}{error&&<div className="error" role="alert">{error}<button className="text-button" onClick={()=>{setError('');if(!demo)void reload()}}>Tentar novamente</button></div>}{loading&&<p role="status">Atualizando dados…</p>}
 {page!=='Usuários'&&<div className="toolbar">{page!=='Visão geral'&&page!=='Alocação'&&<label className="search"><Search size={17}/><input aria-label="Buscar por nome" placeholder="Buscar por nome…" value={search} onChange={e=>setSearch(e.target.value)}/></label>}{(page==='Pacientes'||page==='Triagem')&&<select aria-label="Filtrar situação" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">Todas as situações</option>{statuses.map(s=><option key={s}>{s}</option>)}</select>}{page==='Alunos'&&<select aria-label="Filtrar alunos" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">Todos os alunos</option><option value="pending">Aguardando pacientes</option></select>}{page==='Agenda'&&<><select aria-label="Período da agenda" value={calendarMode} onChange={e=>{setCalendarMode(e.target.value);if(!calendarDate)setCalendarDate(appointmentDay(new Date().toISOString()))}}><option value="all">Todos os períodos</option><option value="day">Dia</option><option value="week">Semana</option></select>{calendarMode!=='all'&&<label className="date-filter">Data <input type="date" value={calendarDate} onChange={e=>setCalendarDate(e.target.value)}/></label>}<select aria-label="Aluno na agenda" value={studentFilter} onChange={e=>setStudentFilter(e.target.value)}><option value="">Todos os alunos</option>{data.students.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></>}{(page==='Pacientes'||page==='Triagem'||page==='Visão geral')&&<label className="export-option"><input type="checkbox" checked={includeSensitive} onChange={e=>setIncludeSensitive(e.target.checked)}/>Incluir motivo da busca na exportação</label>}<div className="toolbar-actions"><button className="secondary" onClick={()=>setExcel(true)}><Upload size={16}/>Importar Excel</button><button className="secondary" onClick={()=>void exportCurrent()} disabled={busy}><Download size={16}/>Exportar Excel</button></div></div>}
 {page==='Visão geral'&&<><section className="stats">{[{label:'Pacientes cadastrados',value:data.patients.length,note:'Uma visão de toda a jornada',icon:Users},{label:'Aguardando triagem',value:data.patients.filter(p=>['Aguardando contato','Triagem agendada'].includes(p.status)).length,note:'Próximos contatos da recepção',icon:ClipboardList},{label:'Em atendimento',value:data.assignments.filter(a=>!a.ended_on).length,note:'Vínculos ativos',icon:Activity},{label:'Alunos aguardando pacientes',value:pendingStudents.length,note:'Com menos de 2 pacientes',icon:GraduationCap}].map(s=><article className="stat" key={s.label}><span>{s.label}<s.icon size={18}/></span><strong>{s.value}</strong><small>{s.note}</small></article>)}</section><div className="dashboard-grid"><section className="panel"><div className="panel-heading"><div><h2>Próximos atendimentos</h2><p>A agenda da recepção, em um só lugar</p></div><button className="text-button" onClick={()=>go('Agenda')}>Ver agenda <ArrowRight size={16}/></button></div>{appointments.filter(a=>a.status==='Agendado'&&new Date(a.end)>new Date()).slice(0,4).map(a=><button className="appointment appointment-button" key={a.id} onClick={()=>setModal({table:'appointments',record:a})}><div className="time">{time(a.start)}<small>{date(a.start)}</small></div><span className="avatar">{initials(data.patients.find(p=>p.id===a.patient_id)?.name||'')}</span><div className="appointment-person"><b>{data.patients.find(p=>p.id===a.patient_id)?.name}</b><small>{data.students.find(s=>s.id===a.student_id)?.name||'Aluno a definir'}</small></div><span className={a.kind==='Triagem'?'badge amber':'badge green'}>{a.kind}</span></button>)}{!appointments.some(a=>a.status==='Agendado'&&new Date(a.end)>new Date())&&<p className="empty">Nenhum atendimento futuro. Agende o próximo encontro.</p>}</section><section className="panel green-panel"><Link2 size={27}/><p className="eyebrow">DISTRIBUIÇÃO DE PACIENTES</p><h2>Um próximo encontro<br/>começa por aqui.</h2><p>Encontre alunos com horários compatíveis e organize novos vínculos.</p><button onClick={()=>go('Alocação')}>Organizar alocação <ArrowRight size={18}/></button></section></div><section className="panel"><div className="panel-heading"><div><h2>Aguardando o próximo passo</h2><p>Pacientes que precisam de atenção da recepção</p></div><button className="text-button" onClick={()=>go('Triagem')}>Ver triagem →</button></div><PatientTable patients={data.patients.filter(p=>['Aguardando contato','Triagem agendada','Aguardando vaga'].includes(p.status)).slice(0,5)} onEdit={p=>setModal({table:'patients',record:p})}/></section></>}
 {(page==='Pacientes'||page==='Triagem')&&<section className="panel"><div className="panel-heading"><h2>{patientRows.length} {page==='Triagem'?'na fila de triagem':'pacientes'}</h2></div><PatientTable patients={patientRows} onEdit={p=>setModal({table:'patients',record:p})}/></section>}
 {page==='Alunos'&&<div className="student-grid">{studentRows.map(s=><article className="panel student-card" key={s.id}><div className="student-title"><span className="avatar">{initials(s.name)}</span><div><h2>{s.name}</h2><span className="muted">{s.semester}</span></div></div><p className="muted">Supervisão · {s.supervisor}</p><div className="capacity"><strong>{activeCount(data,s.id)}</strong><span>pacientes ativos</span><span className={'badge '+(s.reconciled&&activeCount(data,s.id)<2?'amber':'')}>{!s.reconciled?'Conferir vínculos':activeCount(data,s.id)<2?'Aguardando pacientes':'Distribuição atendida'}</span></div><p className="muted">{s.availability.length} horários disponíveis na semana</p><div className="card-actions"><button className="text-button" onClick={()=>setModal({table:'students',record:s})}>Editar cadastro</button><button className="text-button" onClick={()=>go('Alocação')}>Adicionar paciente →</button></div></article>)}{!studentRows.length&&<p className="empty">Nenhum aluno encontrado.</p>}</div>}
 {page==='Agenda'&&<section className="panel"><div className="panel-heading"><h2>{appointments.length} agendamentos</h2><span className="muted">Horário de Porto Alegre</span></div><div className="table-wrap"><table><thead><tr><th>Data / horário</th><th>Paciente</th><th>Aluno</th><th>Tipo / sala</th><th>Situação</th><th>Ação</th></tr></thead><tbody>{appointments.map(a=><tr key={a.id}><td><b>{date(a.start)}</b><small>{time(a.start)}–{time(a.end)}</small></td><td>{data.patients.find(p=>p.id===a.patient_id)?.name}</td><td>{data.students.find(s=>s.id===a.student_id)?.name||'A definir'}</td><td>{a.kind}<small>{a.room||'Sala a definir'}</small></td><td><span className="badge">{a.status}</span></td><td><button className="text-button" onClick={()=>setModal({table:'appointments',record:a})}>Editar / reagendar</button></td></tr>)}</tbody></table>{!appointments.length&&<p className="empty">Nenhum agendamento neste filtro.</p>}</div></section>}
 {page==='Alocação'&&<><section className="panel allocation"><h2>Encontre o próximo vínculo</h2><p className="muted">Selecione um paciente para comparar disponibilidades. Confirme o horário com ele antes de agendar.</p><label className="field"><span>Paciente sem vínculo ativo</span><select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Selecione um paciente</option>{data.patients.filter(p=>!data.assignments.some(a=>a.patient_id===p.id&&!a.ended_on)&&!['Encerrado','Desistência','Encaminhado'].includes(p.status)).map(p=><option key={p.id} value={p.id}>{p.name} · {p.status}</option>)}</select></label>{chosen&&!eligible(chosen)&&<p className="error">Confira idade e vínculos institucionais no cadastro antes de alocar.</p>}{chosen&&<div className="match-list">{[...data.students].sort((a,b)=>activeCount(data,a.id)-activeCount(data,b.id)).map(s=><div className="match" key={s.id}><div><b>{s.name}</b><p>{s.reconciled?`${activeCount(data,s.id)} pacientes ativos`:'Conferir vínculos existentes'} · {s.supervisor}</p><span className="badge green">{compatible(chosen,s).length?compatible(chosen,s).join(' · '):'Sem horário compatível informado'}</span></div><button className="primary" disabled={busy||!eligible(chosen)||!s.institution_verified} onClick={()=>void assign(s)}>Vincular</button></div>)}</div>}</section><section className="panel history"><div className="panel-heading"><div><h2>Vínculos e histórico</h2><p>Encerramentos preservam a trajetória do paciente.</p></div></div><div className="table-wrap"><table><thead><tr><th>Paciente</th><th>Aluno</th><th>Início</th><th>Situação</th><th>Ação / motivo</th></tr></thead><tbody>{data.assignments.map(a=><tr key={a.id}><td>{data.patients.find(p=>p.id===a.patient_id)?.name}</td><td>{data.students.find(s=>s.id===a.student_id)?.name}</td><td>{a.started_on.split('-').reverse().join('/')}</td><td><span className={'badge '+(!a.ended_on?'green':'')}>{a.ended_on?'Encerrado':'Ativo'}</span></td><td>{a.ended_on?a.reason:<button className="text-button" onClick={()=>setModal({table:'assignments',record:a})}>Encerrar vínculo</button>}</td></tr>)}</tbody></table>{!data.assignments.length&&<p className="empty">Nenhum vínculo registrado.</p>}</div></section></>}
 {page==='Usuários'&&(operator.role==='admin'?<section className="panel allocation"><h2>Convidar uma pessoa para a recepção</h2><p className="muted">Novas contas recebem o perfil de operadora. Apenas você pode criar usuários.</p><form onSubmit={invite} className="form-grid"><label className="field"><span>Nome</span><input name="name" required/></label><label className="field"><span>E-mail</span><input type="email" name="email" required/></label><div className="full"><button className="primary" disabled={busy}>Enviar convite</button></div></form><h2 className="history">Contas autorizadas</h2>{(demo?[{id:'demo',name:'Administrador (demonstração)',role:'admin',active:true}]:members).map(m=><div className="match" key={m.id}><b>{m.name}</b><span className="badge">{m.role==='admin'?'Administrador':'Operadora'} · {m.active?'Ativo':'Inativo'}</span></div>)}</section>:<p className="error">Esta página é exclusiva do administrador.</p>)}
 <footer>SINAPSI <span>Clínica-escola de Psicologia · Atitus Educação</span></footer></div></main><dialog ref={dialog} onCancel={()=>{setModal(null);setExcel(false)}}><div className="modal-heading"><div><p className="eyebrow">SINAPSI</p><h2>{excel?'Importar planilha':modal?.table==='patients'?'Cadastro do paciente':modal?.table==='students'?'Cadastro do aluno':modal?.table==='assignments'?'Encerrar vínculo':'Agendamento'}</h2></div><button className="icon-button" aria-label="Fechar" onClick={()=>{setModal(null);setExcel(false)}}><X/></button></div>{modal&&<RecordForm key={modal.record?.id||modal.table} table={modal.table} record={modal.record} data={data} onSave={save} onClose={()=>setModal(null)}/>} {excel&&<ExcelPanel initial={pageTable[page]||'patients'} data={data} onSave={save} onClose={()=>setExcel(false)}/>}</dialog></div>
}
function PatientTable({patients,onEdit}:{patients:Patient[];onEdit:(p:Patient)=>void}){return <div className="table-wrap"><table><thead><tr><th>Paciente</th><th>Situação</th><th>Disponibilidade</th><th>Renda por pessoa</th><th>Ação</th></tr></thead><tbody>{patients.map(p=><tr key={p.id}><td><b>{p.name}</b><small>{p.age} anos na inscrição</small></td><td><span className={'badge '+(p.status==='Em atendimento'?'green':'amber')}>{p.status}</span></td><td>{p.availability.length?p.availability.slice(0,2).join(' · '):'A conferir'}{p.availability.length>2&&<small>+{p.availability.length-2} opções</small>}</td><td>{perCapita(p)===null?'A conferir':perCapita(p)!.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</td><td><button className="text-button" onClick={()=>onEdit(p)}>Abrir cadastro <ArrowRight size={15}/></button></td></tr>)}</tbody></table>{!patients.length&&<p className="empty">Nenhum paciente encontrado. Cadastre ou importe uma planilha.</p>}</div>}
